# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5f87f88be1b71b438c0840204ac7848e7f7d5762e16e784a473b77196a308a718944122f0ac1a8794d32b03f7725858eb5d5ad9037d18ac296fbf9ba5f0377f2

test:
  secret_key_base: fc26e4bbff20951aeed8e4874675984a395a1cfac461c1948b4ccbf9a9f376dc392c116b66c3c27e1c1bef9b98d817a3583e9782d3cd082532ded28d634622c6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
